version: '3'
services:
  strapi:
    build: .
    container_name: strapi-app
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: StrapiUser
      DATABASE_PASSWORD: 123456
      DATABASE_SSL: 'false'
      NODE_ENV: production
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: StrapiUser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
