version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: StrapiUser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Strapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
